$directories = @(
    "src/assets/images",
    "src/assets/icons",
    "src/assets/logos",
    "src/assets/fonts",
    "src/components/common",
    "src/components/layout",
    "src/components/charts",
    "src/context",
    "src/hooks",
    "src/services",
    "src/utils",
    "src/routes",
    "src/pages/auth",
    "src/pages/fleetManager",
    "src/pages/driver",
    "src/pages/safetyOfficer",
    "src/pages/financialAnalyst"
)

foreach ($dir in $directories) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$files = @(
    "src/components/common/Button.jsx",
    "src/components/common/Card.jsx",
    "src/components/common/Modal.jsx",
    "src/components/common/Loader.jsx",
    "src/components/common/Table.jsx",
    "src/components/common/Pagination.jsx",
    "src/components/common/SearchBar.jsx",
    "src/components/common/StatusBadge.jsx",
    "src/components/common/EmptyState.jsx",
    "src/components/layout/Navbar.jsx",
    "src/components/layout/Sidebar.jsx",
    "src/components/layout/MobileSidebar.jsx",
    "src/components/layout/Footer.jsx",
    "src/components/layout/DashboardLayout.jsx",
    "src/components/charts/BarChart.jsx",
    "src/components/charts/LineChart.jsx",
    "src/components/charts/PieChart.jsx",
    "src/components/charts/AreaChart.jsx",
    "src/context/AuthContext.jsx",
    "src/context/ThemeContext.jsx",
    "src/context/NotificationContext.jsx",
    "src/hooks/useAuth.js",
    "src/hooks/useTheme.js",
    "src/hooks/useFetch.js",
    "src/services/api.js",
    "src/services/authService.js",
    "src/services/vehicleService.js",
    "src/services/driverService.js",
    "src/services/tripService.js",
    "src/services/maintenanceService.js",
    "src/services/expenseService.js",
    "src/services/reportService.js",
    "src/services/dashboardService.js",
    "src/utils/constants.js",
    "src/utils/helpers.js",
    "src/utils/validators.js",
    "src/utils/dateFormatter.js",
    "src/utils/auth.js",
    "src/routes/AppRoutes.jsx",
    "src/routes/ProtectedRoute.jsx",
    "src/routes/RoleRoute.jsx",
    "src/pages/auth/Login.jsx",
    "src/pages/auth/Register.jsx",
    "src/pages/auth/Unauthorized.jsx",
    "src/pages/fleetManager/Dashboard.jsx",
    "src/pages/fleetManager/Vehicles.jsx",
    "src/pages/fleetManager/VehicleDetails.jsx",
    "src/pages/fleetManager/Drivers.jsx",
    "src/pages/fleetManager/DriverDetails.jsx",
    "src/pages/fleetManager/DispatchTrips.jsx",
    "src/pages/fleetManager/DispatchHistory.jsx",
    "src/pages/fleetManager/Maintenance.jsx",
    "src/pages/fleetManager/FuelLogs.jsx",
    "src/pages/fleetManager/Expenses.jsx",
    "src/pages/fleetManager/Reports.jsx",
    "src/pages/fleetManager/Settings.jsx",
    "src/pages/fleetManager/Profile.jsx",
    "src/pages/driver/Dashboard.jsx",
    "src/pages/driver/MyTrips.jsx",
    "src/pages/driver/CurrentTrip.jsx",
    "src/pages/driver/FuelLogs.jsx",
    "src/pages/driver/TripHistory.jsx",
    "src/pages/driver/Settings.jsx",
    "src/pages/driver/Profile.jsx",
    "src/pages/safetyOfficer/Dashboard.jsx",
    "src/pages/safetyOfficer/DriverCompliance.jsx",
    "src/pages/safetyOfficer/LicenseMonitoring.jsx",
    "src/pages/safetyOfficer/VehicleSafety.jsx",
    "src/pages/safetyOfficer/IncidentReports.jsx",
    "src/pages/safetyOfficer/SafetyReports.jsx",
    "src/pages/safetyOfficer/Settings.jsx",
    "src/pages/safetyOfficer/Profile.jsx",
    "src/pages/financialAnalyst/Dashboard.jsx",
    "src/pages/financialAnalyst/FuelReports.jsx",
    "src/pages/financialAnalyst/OperationalCost.jsx",
    "src/pages/financialAnalyst/VehicleROI.jsx",
    "src/pages/financialAnalyst/ExpenseManagement.jsx",
    "src/pages/financialAnalyst/BudgetReports.jsx",
    "src/pages/financialAnalyst/ExportReports.jsx",
    "src/pages/financialAnalyst/Settings.jsx",
    "src/pages/financialAnalyst/Profile.jsx"
)

foreach ($file in $files) {
    if (-not (Test-Path $file)) {
        New-Item -ItemType File -Force -Path $file | Out-Null
    }
}
Write-Output "Scaffold complete"
